PACKAGE_NAME="iwchaos"
PACKAGE_VERSION="0.1.0"
BUILT_MODULE_NAME[0]="iwchaos"
DEST_MODULE_LOCATION[0]="/updates"
AUTOINSTALL="yes"
REMAKE_INITRD="no"

MAKE[0]="make modules KERNEL_SRC=${kernel_source_dir}"
CLEAN="make clean"
